services:
  - type: web
    name: gh-profile-stats
    runtime: node
    repo: https://github.com/SoufianoDev/gh-profile-stats
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: GITHUB_TOKEN
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
